name: novel_app
description: "A Flutter project where people can write and publish their own stories with AI's aid"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  go_router: ^14.2.7
  io: ^1.0.4
  intl: ^0.19.0
  email_validator: ^3.0.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_quill: ^10.7.5
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.2
  firebase_app_check: ^0.3.1+3
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  google_generative_ai: ^0.4.6
  flutter_widget_from_html: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
          style: normal
        - asset: assets/fonts/Lora-Italic.ttf
          style: italic
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
          weight: 400
          style: normal

  assets:
    - assets/icons/ic_sparkle1.svg
    - assets/icons/ic_sparkle2.svg
    - assets/icons/ic_chat_bubble.svg
    - assets/images/sky.jpg
    - .env
